services:
  milanauth:
    image: ${DOCKER_REGISTRY-}milanauth
    build:
      context: MilanAuth
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "7002:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: milanauth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
